### ISSUE TITLE
Disitrubte PyPI sdist for 0.92

### ISSUE THREAD

**Issue by koobs** [sadaszewski/focker#2]
While looking to fetch the GitHub sources for 0.91 (See #1), I noticed the 0.92 git tag. The current focker PyPI (sdist) version is 0.91.

It would be create, if 0.92 is 'complete', to update the PyPI sdist to 0.92, from the revision at which that version was tagged

**Comment by sadaszewski** [comment]
I am not sure I fully understand. I have tagged and released the current
revision as 0.95 and I think it would be easier to just pip install
git+https:// rather than sdist. I think to drop PyPi altogether as it only
complicates my workflow.
