### ISSUE TITLE
Error on zfs list

### ISSUE THREAD

**Issue by mike-pt** [sadaszewski/focker#4]
Error:
```
focker bootstrap
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/focker/focker.py", line 211, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/focker/focker.py", line 200, in main
    zfs_init()
  File "/usr/local/lib/python3.7/site-packages/focker/zfs.py", line 193, in zfs_init
    poolname = zfs_poolname()
  File "/usr/local/lib/python3.7/site-packages/focker/zfs.py", line 185, in zfs_poolname
    poolname = zfs_parse_output(['zfs', 'list', '-H', '/'])
  File "/usr/local/lib/python3.7/site-packages/focker/zfs.py", line 26, in zfs_parse_output
    out = zfs_run(command)
  File "/usr/local/lib/python3.7/site-packages/focker/zfs.py", line 21, in zfs_run
    out = subprocess.check_output(command, stderr=subprocess.STDOUT)
  File "/usr/local/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['zfs', 'list', '-H', '/']' returned non-zero exit status 1.
```

I have a zfs pool/dataset in /data (not /) I suppose that's why this fails, but I couldn't figure how to tell focker to look in /data

in fact, I get this error even when not passing any arg

**Comment by sadaszewski** [comment]
This is indeed a limitation of Focker at the moment. It assumes a ZFS root.
I will leave this issue open and deal with it in the next run of fixes. You
could also try to fix it and submit a pull request. I would be more than
happy to merge it.

**Comment by mike-pt** [comment]
I don't have much time during the week but I can try in the weekend, should we simply look at the output without / or allow this to be set via env/param? 

i.e. the user would need to provide the dataset he/she wants to use...

I could also go the easy way and  use zfs list -d 0 -H (that will fix it for me and others with a single dataset regardless of the name :D )

**Comment by sadaszewski** [comment]
I think it should most definitely be configurable. The options are:

1. a config file (e.g., /etc/focker, ~/.config/focker)
2. environment variable (export FOCKER_POOLNAME=zroot)
3. command-line switches

Actually, probably all three should be supported for flexibility. The order of evaluation should be as above, i.e. ~/.config/focker overrides /etc/focker, env. var overrides config files, command line overrides env. vars.

There are other parameters as well that are candidates for this type of configuration, namely the network interface and the default IP address / IP range for ad-hoc containers.

Therefore, I think a generic mechanism should be added to Focker that would wrap the command line parser created by focker.py/create_parser() and try to load the values from files/env. vars if not specified on the command line.

If you could give it a try to write such a wrapper that would be truly amazing.

**Comment by mike-pt** [comment]
Sadly I don't think I have the time for all of that, but I did poke around it to get just the argeparse stuff working.

But to my point above on a single dataset setup this would work if we use:
```
diff --git a/focker/zfs.py b/focker/zfs.py
index 8d22536..6dfccf6 100644
--- a/focker/zfs.py
+++ b/focker/zfs.py
@@ -201,7 +201,7 @@ def zfs_name(path):
 
 
 def zfs_poolname():
-    poolname = zfs_parse_output(['zfs', 'list', '-H', '/'])
+    poolname = zfs_parse_output(['zfs', 'list', '-H', '-d', '0'])
 ```

btw I also notice that when editing the files on BSD I get ^M  for new lines, I can fix it with sed but I suppose it should be fixed upstream

**Comment by mike-pt** [comment]
happy to PR this  https://github.com/mike-pt/focker/commit/b34cabf60fa77b6639deb5d37e5dabd140fb36fb if you're ok with it.

**Comment by sadaszewski** [comment]
Should be solved now as the Focker root dataset can be specified in the configuration.
