### ISSUE TITLE
line 199, in command_compose_run     raise NotImplementedError

### ISSUE THREAD

**Issue by gallexme** [sadaszewski/focker#5]
`sudo focker compose r focker-compose.yml clone
Waiting for /var/lock/focker.lock ...
Lock acquired.
poolname: zroot
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/focker/focker.py", line 266, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/focker/focker.py", line 262, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/focker/compose.py", line 199, in command_compose_run
    raise NotImplemented`

Am Im missing something?
i followed the guide here?
https://github.com/sadaszewski/focker#commands
and https://github.com/sadaszewski/focker#focker-composeyml-syntax

**Comment by sadaszewski** [comment]
Hi gallexme, Apologies, *compose run* is not implemented and I was thinking
of removing it. Wouldn't a Makefile take better care of any additional
commands you would like to run? OTOH to build the compositions you need to
execute *focker* *compose* *build*. Are you sure you were after the *run*
command? Best, -- Stanislaw

**Comment by sadaszewski** [comment]
A nice end-to-end example can be found here:
https://github.com/sadaszewski/focker/tree/master/example/scm-manager

**Comment by gallexme** [comment]
Thanks, personally switched to BastilleBSD now, feels more feature complete

**Comment by sadaszewski** [comment]
Sounds good. Please keep in mind that BastilleBSD is just a collection of shell scripts with completely different functionality than Focker and without unit testing. If it works for you it is great.

**Comment by gallexme** [comment]
If focker would support it would be great aswell yes,

What I need is ephermal  build containers in 32bit FreeBSD 12,  and FreeBSD
12 64bit (both on 64bit host)
 With fixed numbers of  pkg installed on each (possibly definable with
fockerfile)

A dynamic route between build container and outside world over a single
public IP, (for example port 2020 goes to to ssh port 22 in a container),
for remote coding tools (clion)


An easy to use multi node networking thkng, so that I can run mysql on 3
different servers with focker, but I guess that could be also manually done
quite easily

And around 5 Single process apps  in ephermal  containers, where I can bump
the scaling number with maybe the focker compose, or even better with a api
so I can scale em up directly from external world depending on demands


But it seems there's no solution for that on FreeBSD yet, so we kinda stuck
with bastille (cause 32bit jails) + easyness  thanks to pf rdr port
forwarding

So prolly gonna port our servers over near future to maybe a kubernetes
solution using kubevirt to run FreeBSD distributed :(
